### ISSUE TITLE
Undefined function entity_save()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/weight#2]
There's no `entity_save()` function in Backdrop - I'm getting this error when trying to sort weights in a view. Instead it looks like the code already loads `$entity` so you might be able to just do `$entity->save()`.

**Comment by herbdool** [comment]
@argiepiano I've got a PR which fixes this issue https://github.com/backdrop-contrib/weight/pull/4

**Comment by argiepiano** [comment]
@herbdool, thanks for catching this issue. Since `weight` depends on `entity_plus`, it is preferable to use the function entity_plus_save defined there, which is the equivalent of Drupal's `entity_save`. I will make those change it and merge them into the master branch in a second.  `entity_plus_save` is preferable because it checks the entity definition for a specific save callback and for a save function in the entity controller.

**Comment by herbdool** [comment]
Thanks for making the fix @argiepiano.

I still don't think `entity_plus` is necessary in this case (and this seems to be the only place where you're calling a function from that module). If you look at the `save()` method on `Entity` https://docs.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.class.inc/function/Entity%3A%3Asave/1 it already fetches the controller https://docs.backdropcms.org/api/backdrop/core%21modules%21entity%21entity.module/function/entity_get_controller/1. 

```
  public function save() {
    return entity_get_controller($this->entityType())->save($this);
  }
```

I don't think this was available in Drupal 7 which probably explains why this module was calling `entity_save` previously. Backdrop core now includes a large chunk of the former contrib module `Entity`. The core modules User, Node, Taxonomy all have controllers with the save method that would get called when using `$node->save()` for example.

You also mention a "save callback" which I'm not sure what you mean, but as far as I can tell just using `$entity->save()` here would do the trick.

**Comment by argiepiano** [comment]
Thanks for the additional comment, @herbdool ! 

I see your point. We could simply eliminate the `entity_plus` dependence and use what you propose. 

At this point the only benefit of using `entity_plus_save` is that this function provides a bit more flexibility than calling the `save` method for the entity class directly, ESPECIALLY for custom entities. Take a look at `entity_plus_save()`... The first thing it does is try to use the `save` method of the entity (which is what you are suggesting). If the entity does not have a save method (which could happen for custom entities that do not extend `Entity`), then it calls the 'save callback' callback function defined in hook_entity_info for the custom entity, or the `save` method directly from the controller if it implements `EntityPlusControllerInterface`. 

So, the question is: is it worth keeping the `entity_plus` dependency (and the call to `entity_plus_save()` just for that convenience feature? Any thoughts on that?

**Comment by herbdool** [comment]
Is it even possible to create a custom entity in Backdrop without extending Entity? I'm not certain but it might be difficult. Might quickly get a fatal error now.

**Comment by argiepiano** [comment]
@herbdool I think you are right. I will remove the dependency and use `$entity->save()` as you suggested.

**Comment by argiepiano** [comment]
Done - I removed the `entity_plus` dependency and changed the Views handler. @herbdool would you mind doing a quick test before I release a new version? Thanks for all the work!

**Comment by herbdool** [comment]
@argiepiano I've tested it with nodes and it works. Thanks!

**Comment by argiepiano** [comment]
Tested with a custom entity and it works also. Thanks!
